canvas-token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
gitlab-host: https://git-classes.mst.edu/
namespace: 2016-Fall-CS1001
# we recommend using one of the import commands to automatically populate the roster
roster:
- name: Smith, John
  section: A
  username: abc123
- name: Smith, Jane
  section: A
  username: xyz123
semester: 2016FS
token: xxxxxxxxxxxxxxxx
